version: "3.7"

services:

    mysql:
        image: mysql:8
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Password123#
        ports:
            - "3306:3306"
        volumes:
            - ./data:/docker-entrypoint-initdb.d
